image: registry.gitlab.com/ecloud/ci-runners/native:2_0_0

variables:
  PROJECT: "proxy-tcp"

test_master:
  stage: test
  script:
    - npm version
    - npm install
    - npm run spec
    - npm run lint
  artifacts:
    paths:
      - node_modules
  only:
    - master@ECloud/proxy-tcp
    - triggers

test:
  stage: test
  script:
    - npm version
    - npm install
    - npm run spec
    - npm run lint
  except:
    - master@ECloud/proxy-tcp
    - triggers

