image: registry.gitlab.com/ecloud/ci-runners/native:2_0_0

stages:
  - test
  - release

before_script:
  - npm version
  - npm install

variables:
  PROJECT: "proxy-tcp"

test_master:
  stage: test
  script:
    - npm test
    - npm run lint
  artifacts:
    paths:
      - node_modules
  only:
    - master@ECloud/proxy-tcp
    - triggers

test:
  stage: test
  script:
    - npm test
    - npm run lint
  except:
    - master@ECloud/proxy-tcp
    - triggers

publish:
  stage: release
  script:
    - |
      BEFORE=$( npx -c 'echo "$npm_package_version"' )
      npx semantic-release
      AFTER=$( npx -c 'echo "$npm_package_version"' )
      if [[ $BEFORE != $AFTER ]]; then
        LAST_COMMIT=$( git rev-parse HEAD ) && git checkout master && git merge $LAST_COMMIT
        git remote add gitlab https://oauth2:$GLB_TOKEN@gitlab.com/$CI_PROJECT_PATH.git
        git push gitlab master
        LAST_VERSION=$( git describe --tags ) && git push gitlab $LAST_VERSION
      fi
  only:
    - master
